version: '2'

# 容器运行网络
networks:
  solonet:

services:
  # orderer.yzm.com:7050
  orderer.yzm.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.yzm.com
    container_name: orderer.yzm.com
    networks:
      - solonet
  # peer0.orga.com:7051
  peer0.orga.com:
    container_name: peer0.orga.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.orga.com
    networks:
      - solonet
  # peer0.orgb.com:8051
  peer0.orgb.com:
    container_name: peer0.orgb.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.orgb.com
    networks:
      - solonet
  # cli
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.0.0
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.orga.com:7051
      - CORE_PEER_LOCALMSPID=OrgAMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.com/peers/peer0.orga.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.com/peers/peer0.orga.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.com/peers/peer0.orga.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.com/users/Admin@orga.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/pipapa/chaincode/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.yzm.com
      - peer0.orga.com
      - peer0.orgb.com
    networks:
      - solonet
