test:
  name: pbft-network
  description: pbft-network
  workers:
    type: local
    number: 5

  rounds:
  - label: open
    description: open
    txNumber: 10000
    rateControl:
      type: fixed-rate
      opts:
        tps: 1000
    callback: ../chaincode/demo/callback/open.js

  - label: transfer
    description: transfer
    txNumber: 5000
    rateControl:
      type: fixed-rate
      opts:
        tps: 1000
    callback: ../chaincode/demo/callback/transfer.js

  - label: query
    description: query
    txNumber: 10000
    rateControl:
      type: fixed-rate
      opts:
        tps: 1000
    callback: ../chaincode/demo/callback/query.js

  - label: delete
    description: delete
    txNumber: 10000
    rateControl:
      type: fixed-rate
      opts:
        tps: 1000
    callback: ../chaincode/demo/callback/delete.js

monitor:
  interval: 1
  type: 
    - docker
  docker:
    containers:
    - peer0.orga.com
    - orderer0.yzm.com
    - orderer1.yzm.com
    - orderer2.yzm.com
    - orderer3.yzm.com
